### PR TITLE
Include target attribute in template.

### PR DESCRIPTION
**Pull request by henrahmagix**
Forgot to do this for the last feature, #7.

@incuna/js Please merge, ta!

### CODE REVIEW

**Comment by grahamgilchrist** [comment]
What happens if there was no target originally? will `target="undefined" have strange behaviour?

**Comment by henrahmagix** [comment]
It'll output as `<a href="/#/"` target></a>`, which is fine. I can't find any documentation saying so, but I think it's like any attribute that isn't a boolean field: having the attribute without a value and having no attribute is the same result: `undefined`, not used, ignored.

**Comment by henrahmagix** [comment]
Thanks!

**Comment by henrahmagix** [comment]
Release as `1.2.1` https://github.com/incuna/angular-external-link-interceptor/releases/tag/1.2.1

**Pull request merged**
